############################
## CHANGE THESE
############################

baseURL: "https://GionaBolzer.github.io/blog"
title: blog

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
